package Parking;

import java.util.*;

public class Users {
 private String name;
 private String password;
 private String email;
 private String phone;
 private String address;
 private String type;
 private String id;
 private String status;
 private String car;
 private String carNumber;
 private String carType;
 private String carColor;
 private String carStatus;
 private String carId;
 private String carParkingId;
 private String carParkingName;
 private String carParkingAddress;
 private String carParkingStatus;
 private String carParkingType;
 private String carParkingPrice;
 private String carParkingTime;
 private String carParkingDate;
 private String carParkingDuration;
 private String carParkingTotal;
 private String carParkingIdUser;
 private String carParkingIdCar;
 private String carParkingIdParking;
 private String carParkingIdStatus;
 private String carParkingIdType;
 private String carParkingIdPrice;
 private String carParkingIdTime;
 private String carParkingIdDate;
 private String carParkingIdDuration;
 private String carParkingIdTotal;
 private String carParkingIdPayment;
 private String carParkingIdPaymentStatus;
 private String carParkingIdPaymentDate;
 private String carParkingIdPaymentTime;
 private String carParkingIdPaymentTotal;
 private String carParkingIdPaymentType;
 private String carParkingIdPaymentId;
 private String carParkingIdPaymentStatusPayment;
 private String carParkingIdPaymentStatusParking;
 private String carParkingIdPaymentStatusCar;
 private String carParkingIdPaymentStatusUser;
 private String carParkingIdPaymentStatusType;
 private String carParkingIdPaymentStatusPrice;
 private String carParkingIdPaymentStatusTime;
 private String carParkingIdPaymentStatusDate;
 private String carParkingIdPaymentStatusDuration;
 private String carParkingIdPaymentStatusTotal;
 private String carParkingIdPaymentStatusId;
}
